name: Weather CLI

on:
  push:
    paths:
      - "trainee/nt-r.tuguldur/projects/weather-cli/**"

  pull_request:
    paths:
      - "trainee/nt-r.tuguldur/projects/weather-cli/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: trainee/nt-r.tuguldur/projects/weather-cli

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npm run lint

      - run: npm run build